name: Build REST API
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: Almog_Yuval_Printer_manager_system/printerApplication/printerApplication.iml build
      - name: Build project
        run: npm run build
        working-directory: printerApplication/printerApplication.iml build

