name: Build project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  # Path to the project directory relative to the root of the repository.
  PROJECT_DIR: printerApplication

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
        
    - name: Make gradlew executable
      working-directory: ${{env.PROJECT_DIR}}
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: ${{env.PROJECT_DIR}}
      run: ./gradlew build
